version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: db_ecommerce_monolite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    ports:
      - "5432:5432"

  ecommerce:
    image: ecommerce
    container_name: ecommerce-project
    env_file:
      - secret.env
    environment:
      DB_URL: "jdbc:postgresql://ecommerce-db:5432/db_ecommerce_monolite"
    networks:
      - ecommerce-network
    ports:
      - "8080:8080"

networks:
  ecommerce-network:
    driver: bridge
volumes:
  db_data:


